# Generated by Django 5.2.4 on 2025-09-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='source',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
