# Generated by Django 5.2.4 on 2025-09-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="date",
            new_name="created_on",
        ),
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
