# Generated by Django 5.2.4 on 2025-09-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_cake", "0005_alter_customcake_filling_alter_customcake_flavor"),
    ]

    operations = [
        migrations.AddField(
            model_name="customcake",
            name="needed_date",
            field=models.DateField(
                blank=True,
                help_text="Date you need the cake for (optional).",
                null=True,
            ),
        ),
    ]
