# Generated by Django 5.2.4 on 2025-09-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_productoption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productoption",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
